name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Print Working Directory
      run: |
        pwd
      working-directory: Terraform  # Adjust the working directory

    - name: Terraform Init
      run: terraform init
      working-directory: Terraform  # Adjust the working directory

    - name: Terraform Plan - Prod
      run: |
        set -x
        ls -la  # List files in the current directory for debugging
        terraform plan -var-file=prod.tfvars -out=tfplan
      working-directory: Terraform  # Adjust the working directory

    - name: Show Plan Output - Prod
      run: |
        echo "Prod API Gateway URL: $TF_OUTPUT_API_GATEWAY_URL_PROD"
